### ISSUE TITLE
block duplication with all block

### ISSUE THREAD

**Issue by AlleCraft-alterego** [Lothrazar/GlassCutter#3]
Minecraft Version: 1.16.3

Forge Version: 34.1.25

Mod Version: 2.0.0

Single Player or Server: singleplayer

glass cutter if breack a block (all block can be mine and cannot be mine) you get silktouch  drop and if possible you can get normal drop if tools is correct

**Comment by Lothrazar** [comment]
finally figured this out. this is an edge case where. if you craft an item in 1.0, then upgrade the mod to 2.0, this can happen. but as of 2.0.
 
 
 This bug only happens if you have a glass cutter with Silk touch on it. but, there is no way in the game to apply silk touch without cheating somehow, or the upgrade method mentioned above.  anyway, 2.0.1 coming out soon and thanks for the report
